draft chapter2
astomusic/You-Dont-Know-JS pull request #2
Opened 2019-07-08 08:31 UTC by astomusic

2019-07-09 04:40 UTC, smoonsf submitted a review, later dismissed
몇몇 의견을 남겨보았는데 다 고쳐달라는 뜻은 아니구요 ㅋㅋ 머지한 이후 PR로 추가하면 어떨까 생각되는 부분들을 남겨보았습니다.
수고하셨어용~

2019-07-09 04:40 UTC, smoonsf commented on types & grammar/Chapter2_Values.md
> +  > join, map등은 가능 reverse는 불가
이 부분에서 본문에 _빌려쓴다_ 라는 것이 Array.prototype 에 있는 메소드를 사용한다는 것을 명시해주는게 좋을 것 같습니다. 스트링 변수값에서 직접 .map을 호출할 수 없기 때문에 분리시켜 주어야 혼동하지 않을 것 같아요.

2019-07-09 04:40 UTC, smoonsf commented on types & grammar/Chapter2_Values.md
> +- Number.prototype 사용가능 [Number.rototype](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/prototype)
오타인 것 같네요 :)

2019-07-09 04:40 UTC, smoonsf commented on types & grammar/Chapter2_Values.md
> +0b11110011 === 243 // true 2진법
책에 명확히 설명이 안되어있는 부분이긴 한데 exponential 표현식의 e나 진법 표현시 사용하는 x, o, b 그리고 10진법 이상에서 사용되는 a,b,c 와 같은 문자들이 대소문자 구분 없이 사용 가능하다는 부분이 추가되면 좋을 것 같네요.

2019-07-09 04:40 UTC, smoonsf commented on types & grammar/Chapter2_Values.md
> +42.0 === 42 // true
`42.` 이라는 리터럴도 사용은 가능하니까 표기해두는게 어떨까요? 주석으로 사용 비추천을 써둬도 좋을 것 같구요.

이 표현 때문에 책에서 toFixed 같은 함수 호출에 문제가 될 수 있다고 표현되어 있기도 하네요.

2019-07-09 04:40 UTC, smoonsf commented on types & grammar/Chapter2_Values.md
> +a | 0 // '| 0' 로 32비트 정수로 강제변환
실제 32비트 연산까지 안전하게 처리할 수 있는 범위가 더 적다는 것을 내용에 적어두는 것은 어떨까요?

2019-07-09 04:40 UTC, smoonsf commented on types & grammar/Chapter2_Values.md
> + - 영 (0 / -0)
-0의 존재 이유 정도는 추가해줘도 좋을 것 같네요

2019-07-09 06:19 UTC, yuyuny requested changes

2019-07-09 06:19 UTC, yuyuny commented on types & grammar/Chapter2_Values.md
> +- 숫자가 키인 객체 따라서 string 키도 삽인 가능.
삽입의 오타 아닐까유

2019-07-09 06:26 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +- 숫자가 키인 객체 따라서 string 키도 삽인 가능.
맞네요 ㅋㅋㅋ

2019-07-09 06:27 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +- 숫자가 키인 객체 따라서 string 키도 삽인 가능.
수정해서 push했어요~

2019-07-09 06:27 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> + - 영 (0 / -0)
수정해서 push했어요~

2019-07-09 06:27 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +42.0 === 42 // true
수정해서 push했어요~

2019-07-09 06:28 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +a | 0 // '| 0' 로 32비트 정수로 강제변환
수정해서 push했어요~

2019-07-09 06:28 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +0b11110011 === 243 // true 2진법
수정해서 push했어요~

2019-07-09 06:28 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +- Number.prototype 사용가능 [Number.rototype](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Number/prototype)
수정해서 push했어요~

2019-07-09 06:28 UTC, astomusic commented on types & grammar/Chapter2_Values.md
> +  > join, map등은 가능 reverse는 불가
수정해서 push했어요~

2019-07-09 07:43 UTC, smoonsf approved these changes
🥇  금메달 드립니다

2019-07-11 02:40 UTC, yuyuny approved these changes

2019-07-11 02:45 UTC, merged