Types and grammer/chapter 4 1~2
astomusic/You-Dont-Know-JS pull request #3
Opened 2019-07-16 04:03 UTC by yuyuny

4.1과 4.2를 정리했습니다.

2019-07-17 02:44 UTC, astomusic commented on types & grammar/Chapter4_Coercion.md
> +d; // true
falsy 값외에 값은 모두 truthy값이라는걸 언급해주는게 좋을꺼 같아요.

2019-07-18 03:00 UTC, astomusic submitted a review, later dismissed
👍

2019-07-18 09:52 UTC, hekkim requested changes

2019-07-18 09:52 UTC, hekkim commented on types & grammar/Chapter4_Coercion.md
> +  - `undefined` => `Nan`
`NaN`이 맞을 거 같애요

2019-07-18 13:37 UTC, smoonsf commented on types & grammar/Chapter4_Coercion.md
> +강제성은 유용한 기능일 수도 있고 언어 자체의 결함일 수도 있다.
강제성을 강제변환으로 바꾸는게 좀 더 자연스러울 것 같아요~

2019-07-18 13:40 UTC, smoonsf commented on types & grammar/Chapter4_Coercion.md
> +- 의도적 => 타입 변환
책에서는 명시적 이라는 단어와 타입캐스팅 이라는 말을 썼는데 캐스팅이라는 것에 대한 개발 개념을 이해하기가 더 쉬워서 굳이 변환이라고 번역하지 않도 타입캐스팅 이라고 그대로 사용한 것 같습니다.
여기도 그렇게 바꾸는게 어떨까요?

2019-07-18 13:45 UTC, smoonsf commented on types & grammar/Chapter4_Coercion.md
> +  - 런타임에서 동적으로
여기서는 자바스크립트의 내용과 자바스크립트에 대한 내용이 섞여있어서 약간 혼동을 주는 것 같습니다.
컴파일시점과 런타임시점으로 구분하는 것은 정적 타입언어와 동적 타입언어에서 각각 용어를 구분하는 참고하는 내용이고 `string`, `number`, `boolean`, `object`, `function` 와 관련된 내용은 자바스크립트에 관한 내용이라 분리가 필요할 것 같습니다.

2019-07-18 13:49 UTC, smoonsf commented on types & grammar/Chapter4_Coercion.md
> +  - `object`, `function` 같은 값이 사용되면 강제 변환 없음
본문의 의미가 강제 변환을 통해 변환되어 나오는 결과 값은 `string`, `number`, `boolean` 과 같은 스칼라 원시 값 중 하나가 되고 `object`, `function`과 같은 값으로는 변환되지 않는다는 뜻인 것 같습니다.

2019-07-18 13:57 UTC, smoonsf commented on types & grammar/Chapter4_Coercion.md
> +- `object` => `[object Object]`
object 내부에 [[class]]라는 추상 속성이 있는데 이게 [object 클래스네임] 이렇게 들어간다는 내용이 추가되면 좋겠습니당~

2019-07-21 11:53 UTC, yuyuny commented on types & grammar/Chapter4_Coercion.md
> +  - `object`, `function` 같은 값이 사용되면 강제 변환 없음
오 이 지적 감사합니다. 제가 너무 정리를 이상하게 한 부분이네요!

2019-07-22 05:51 UTC, hekkim approved these changes
:+1:

2019-07-23 08:51 UTC, astomusic approved these changes

2019-07-23 09:20 UTC, merged