Types & Grammar Chapter 3
astomusic/You-Dont-Know-JS pull request #4
Opened 2019-07-16 18:44 UTC by hekkim

2019-07-17 00:55 UTC, smoonsf commented on types & grammar/Chapter3_Natives.md
> +var s = "Hello world!";
생성자 예시를 보여주려면 new String("Hello world!") 가 맞을 것 같습니당

2019-07-17 00:55 UTC, smoonsf commented on types & grammar/Chapter3_Natives.md
> +원시값에는 프로퍼티나 메서드가 없으으므로 `.length`나 `.toString()`을 접그하려면 객체 래퍼로 감싸줘야 되지만  알아서 박싱(래핑)을 해주므로 다음과 같은 코디가 가능하다.
접근하려면 , 코디 이 두 단어가 오타인 것 같네요 :)

2019-07-17 02:47 UTC, astomusic commented on types & grammar/Chapter3_Natives.md
> +또한 이후에 변경될 디폴트 값으로 `Array.prototype`을 사용하지 말자. 위 예제에서 vals 변수를 수정할 경우 결구 `Array.prototype`도 수정되게 된다.
'결구' 오타인듯요 ^^

2019-07-17 06:02 UTC, yuyuny requested changes

2019-07-17 06:02 UTC, yuyuny commented on types & grammar/Chapter3_Natives.md
> +원시값에는 프로퍼티나 메서드가 없으으므로 `.length`나 `.toString()`을 접그하려면 객체 래퍼로 감싸줘야 되지만  알아서 박싱(래핑)을 해주므로 다음과 같은 코디가 가능하다.
`없으으므로` 이것두 오타..

2019-07-17 06:02 UTC, yuyuny commented on types & grammar/Chapter3_Natives.md
> +심벌(Symbol)은 ES6에서 처음 선보인 새로운 원시 값이다. 심벌은 충돌 염려 없이 객체 프로퍼티로 사용 가능한, 특벽한 '유일 값'이다 (절대적으로 유일함이 보장되지는 않는다!).
`특별한`의 오타?

2019-07-18 09:05 UTC, hekkim commented on types & grammar/Chapter3_Natives.md
> +var s = "Hello world!";
수정했습니다

2019-07-18 09:05 UTC, hekkim commented on types & grammar/Chapter3_Natives.md
> +원시값에는 프로퍼티나 메서드가 없으으므로 `.length`나 `.toString()`을 접그하려면 객체 래퍼로 감싸줘야 되지만  알아서 박싱(래핑)을 해주므로 다음과 같은 코디가 가능하다.
수정했습니다

2019-07-18 09:05 UTC, hekkim commented on types & grammar/Chapter3_Natives.md
> +또한 이후에 변경될 디폴트 값으로 `Array.prototype`을 사용하지 말자. 위 예제에서 vals 변수를 수정할 경우 결구 `Array.prototype`도 수정되게 된다.
수정했습니다

2019-07-18 09:05 UTC, hekkim commented on types & grammar/Chapter3_Natives.md
> +심벌(Symbol)은 ES6에서 처음 선보인 새로운 원시 값이다. 심벌은 충돌 염려 없이 객체 프로퍼티로 사용 가능한, 특벽한 '유일 값'이다 (절대적으로 유일함이 보장되지는 않는다!).
수정했습니다

2019-07-18 13:34 UTC, smoonsf commented on types & grammar/Chapter3_Natives.md
> +```
a와 c가 브라우저 별로 어떻게 다른지 케이스를 조금 적어주면 좋을 것 같습니다. 둘 다 예시가 없으니 어떻게 나올지 잘 모를 것 같아요

2019-07-18 13:35 UTC, smoonsf commented on types & grammar/Chapter3_Natives.md
> +프로타입으로 디폴트 값을 세팅하면 이미 내장된 프로토타입을 이용하므로 사소하지만 추가적인 이점이 있다.
프로타입 오타인 것 같아요~

2019-07-20 01:31 UTC, smoonsf submitted a review, later dismissed

2019-07-20 13:38 UTC, hekkim commented on types & grammar/Chapter3_Natives.md
> +```
수정했습니다

2019-07-20 13:38 UTC, hekkim commented on types & grammar/Chapter3_Natives.md
> +프로타입으로 디폴트 값을 세팅하면 이미 내장된 프로토타입을 이용하므로 사소하지만 추가적인 이점이 있다.
수정했습니다

2019-07-22 02:29 UTC, astomusic approved these changes
branch명 grammar가 맞는거 같은데요? ㅎㅎ

2019-07-22 02:29 UTC, astomusic approved these changes
branch명 grammar가 맞는거 같은데요? ㅎㅎ

2019-07-22 05:53 UTC, hekkim commented
그렇네요 ㅋㅋㅋ 브랜치명이 틀렷네요 ㅋㅋㅋ

2019-07-23 08:51 UTC, astomusic approved these changes

2019-07-24 12:56 UTC, smoonsf approved these changes

2019-07-24 12:58 UTC, yuyuny approved these changes

2019-07-27 06:57 UTC, merged